### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by amcdnl** [marklagendijk/gulp-ng-html2js#12]
I was taking a look at using this:

    .pipe(ngHtml2Js({
        moduleName: function (file) {
            var path = file.split('/'),
                folder = path[path.length - 2];
            return folder.replace(/-[a-z]/g, function (match) {
                return match.substr(1).toUpperCase();
            });
        }
    }))

however it errors saying:  http://www.screencast.com/t/218gbvm7ul

I believe you meant to say `file.path.split`...is that correct?

**Comment by avarabei** [comment]
I have the same error:

TypeError: Object #<File> has no method 'split'
    at gulp.src.pipe.pipe.ngHtml2Js.moduleName

**Comment by marklagendijk** [comment]
I corrected this, thanks!
