### ISSUE TITLE
Is it possible to set template id like "directory/filename.tpl.html"?

### ISSUE THREAD

**Issue by r00ger** [marklagendijk/gulp-ng-html2js#13]
At first thanks for the library.
As I understand the _base_ option of File object never used, so file.relative always equals to filename. 
Is there any way to set tpl is like?
```
$templateCache.put("attachment-element/attachment-element-demo.tpl.html", ....)
```

Thanks.

**Comment by marklagendijk** [comment]
If I correctly you can [specify the base](https://github.com/gulpjs/gulp/blob/master/docs/API.md#optionsbase) in your `gulp.src` call, and gulp-ng-html2js then automatically uses this.
