### ISSUE TITLE
module.exports the angular.module()

### ISSUE THREAD

**Issue by lookfirst** [marklagendijk/gulp-ng-html2js#15]
Can I have an option to export the angular module that is created for the template? 

```
module.exports = angular.module("forms.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("forms.tpl.html", "<h5>A form</h5><input type=\"text\">");
}]);
```

The benefit being that I can then do something like this:

```
define(['form.tpl'], function(formTpl) {
    angular.module('forms', [formTpl.name]);
})
```

I'm happy to submit a pull request, I just want to know it'll get integrated and not rejected. =)

**Comment by marklagendijk** [comment]
I just released 0.2.0. With this version you can use a custom template to get this result.
This way everybody can get the exact output he wants, while the API stays simple.

**Comment by lookfirst** [comment]
@marklagendijk Thanks for making it configurable, but this is a pain because now I have to define my own template and I don't get to take advantage of yours. So, when you improve the template in the future, mine won't automatically get the befits. I also don't get the advantage of having unit tests around the templates without writing my own. I understand that you want to keep your API somewhat clean, but this is a library that you've created and I want to take advantage of it without having to override the main purpose of it.

**Comment by lookfirst** [comment]
You also just complicated things by requiring lodash for the templates, which means that a) it is an extra dependency that isn't really necessary and b) if I want to override the template, that I also have to figure out yet another template language. You'd be better off switching to ES6 templates and using babel as the backport. For such a small project, it certainly has gotten over complicated fast.

**Comment by marklagendijk** [comment]
@lookfirst you are trolling, right? I think that the usage of [options.template](https://github.com/marklagendijk/gulp-ng-html2js#optionstemplate) is very straightforward and clearly documented. Also this is an 'advanced' option. It is only needed for border case usages of the plugin.

**Comment by lookfirst** [comment]
Not trolling at all. With my change, my gulpfile looks like this:

`ngHtml2Js({export: 'commonjs'})`

With your change, my gulpfile looks like this:

`
ngHtml2Js({template: "module.exports = angular.module('<%= moduleName %>', []).run(['$templateCache', function($templateCache) {\n" +
    "  $templateCache.put('<%= template.url %>',\n    '<%= template.prettyEscapedContent %>');\n" +
    "}]);\n"})
`

Which one seems more complex and untestable to you?

**Comment by marklagendijk** [comment]
You are right that with the current implementation your code becomes more complex and harder to test. Sorry for that.
The reason I choose for this solution is that in this way people with non-standard use cases (such as yours) can get the exact result they want. In my opinion this strikes the right balance between being simple to use for common use cases, and being powerful enough to handle less common use cases.

**Comment by lookfirst** [comment]
I see your point too, but I don't see my use case as being uncommon. It makes a huge amount of sense to export it as a module so that it can be referred to by name instead of as a hard coded string. There is a reason why angular includes the module name in the object. Let's take advantage of that.

**Comment by amcdnl** [comment]
@marklagendijk I'd like to see this merged as well.

**Comment by OnkelTem** [comment]
@marklagendijk 

Returning module name in `module.exports` — is the canonical way how angular modules expose their API, you can check out any module and see. That said I wonder why you call this "advanced" usage.

Also voting for the PR.

**Comment by lookfirst** [comment]
@OnkelTem My use case example is defined as the first comment in this PR. =)

Another example with angular...

```
import cartTpl from 'js/buy/t/cart.tpl';

let buyModule = angular.module('gl.buy', [cartTpl.name]);
```

It'd be stupid to even have to care what the .name is...

I don't know why @marklagendijk is sadly ignoring this for so long now.

**Comment by lookfirst** [comment]
@OnkelTem Feel free to use my fork (package.json dependency)...

```
    "gulp-ng-html2js": "lookfirst/gulp-ng-html2js#export2",
```
