### ISSUE TITLE
The options.declareModule apparently changes the order between modules and templates

### ISSUE THREAD

**Issue by colares** [marklagendijk/gulp-ng-html2js#19]
The options.declareModule (true by default) was leading me to an error (Failed to load template: ...). Because it injects my app module definition AFTER one of the templaceCache statements in the final .js, forcing them to create a new app module (since mine will only be defined later).

Something like that:

    // gulpfile.js. declareModule: true by default
    ngHtml2js({
        moduleName: "myApp"
    })

    // final app.min.js
    // 0 my directive
    angular.module('myDirectives', []).directive('myDirective', ...
        return {
            templateUrl: 'partials/myDirectivePartial.html'
            // ...

    // 1 my controller
    angular.module('myControllers', []).directive('myController', ...

    // 2 my controller's PARTIAL template cache
    (function(module) {
        try {
          module = angular.module('myApp');
        } catch (e) {
          module = angular.module('myApp', []);
        }
        module.run(['$templateCache', function($templateCache) {
          $templateCache.put('partials/myControllerPartial.html', '<div>...</div>');
        }]);
    })();

    // 3 my app (who binds partial to my controller)
    angular.module('myApp', [...])
        .config(['$routeProvider', function ($routeProvider) {
            $routeProvider.
                when('/', {
                    templateUrl: 'partials/myControllerPartial.html',
                    controller: 'MyControllerCtrl'
                })
                // ...
    }])

    // 4 my directive's PARTIAL template cache
    (function(module) {
        try {
          module = angular.module('myApp');
        } catch (e) {
          module = angular.module('myApp', []);
        }
        module.run(['$templateCache', function($templateCache) {
          $templateCache.put('partials/myDirectivePartial.html', '<div>...</div>');
        }]);
    })();

As a result, myDirective can find partials/myDirectivePartial.html, but myApp can't find partials/myControllerPartial.html.

When I set this option to false, all templaceCache statements are injected in the end of the file -- and now, of course, they do not try to create a new module.

I do not know if I get wrong the idea of this option, but for me, it should false as default. Or, all templaceCache statements should be injected in the end of the file anyway (after a possible module definition before).

Thanks for this lib, very useful! :)

**Comment by marklagendijk** [comment]
I'm afraid you misunderstood the feature. In the above example you should use 'myTemplates' as the module name for the template generation. 
I'm not sure which value makes more sense as a default, but since changing it would be a breaking fix, I don't think it's worth thinking about ;).
