### ISSUE TITLE
Unmet Peer Dependency for LoDash

### ISSUE THREAD

**Issue by nickescallon** [marklagendijk/gulp-ng-html2js#29]
@marklagendijk  
Lodash v3 is no longer supported, and it looks like v4 does not introduce any breaking changes for this package. 

Can we increase the range of the supported lodash dependency to include v4 as proposed here: https://github.com/marklagendijk/gulp-ng-html2js/pull/28 ?

This would avoid `unmet peer dependency` warnings on `npm install` when using a supported version of lodash.

**Comment by smonkey72** [comment]
+1
